#+pagetitle: baby red potato salad

** baby red potato salad

  [[[file:0-recipe-index.org][main recipe page]]]

category: [[[file:c-side.org][side]]]

#+begin_verse
     4 cups baby red potatoes, cut in small pieces
     1/2 cup green bell pepper, finely diced
     1/4 cup red onion, finely diced
     3 scallions, diced
     1 tsp dijon mustard
     1 tbsp extra virgin olive oil
     1 tbsp red wine vinegar
     1 tbsp reduced fat mayonnaise
     salt and fresh pepper
#+end_verse


 Boil potatoes in salted water until soft, approx 10 minutes. Drain and
 let cool.

 While the potatoes are boiling, combine red onion, green pepper,
 mustard, olive oil, vinegar and mayonnaise and season with salt and
 pepper. Mix well and let the flavors marinade while the potatoes
 cook. Once the potatoes are done and cool, mix into the bowl and add
 scallions and additional salt and pepper to taste. Serve room
 temperature or refrigerate until ready to serve.

 source: http://www.skinnytaste.com/2009/06/baby-red-potato-salad.html

 - vacation May 2018: added some paprika
