#+pagetitle: black bean burgers

** black bean burgers

  [[[file:0-recipe-index.org][main recipe page]]]

category: [[[file:c-beans.org][beans]]]

 Ingredients

     * 1/2 medium yellow onion, roughly chopped
     * 1 tablespoon chopped garlic
     * 2 (15-ounce) cans black beans, rinsed and drained, divided
     * 2 tablespoons freshly chopped cilantro leaves
     * 2 teaspoons freshly chopped parsley leaves
     * 1 egg
     * 1/2 teaspoon red pepper flakes
     * 1/2 cup bread crumbs
     * Salt and fresh ground black pepper
     * 4 hamburger rolls

 Optional Toppings:

     * 1 tomato, sliced
     * 4 small Romaine lettuce leaves, or any other type you have on hand
     * 1/4 cup ketchup

 Directions

 Heat a grill or grill pan over medium-low heat.

 In a food processor, pulse onion and garlic until finely chopped. Add
 1 can black beans, cilantro, parsley, egg, and red pepper flakes and
 pulse to combine.

 Transfer mixture to a large mixing bowl, add the remaining can of
 black beans and the bread crumbs. Season with salt and pepper, to
 taste, and mix until well combined.

 Reserve 1/3 of the black bean mixture for Round 2 Recipe. Divide
 remaining mixture into 4 portions and form into patties. Place on hot
 oiled grill over medium-low heat and cook about 6 minutes a side or
 until heated through. Toast hamburger buns on a grill. Place a burger
 on the bottom of each bun. Top with lettuce, tomato and ketchup. Cover
 the burgers with the top of the bun and serve.

 source:  food network
