#+pagetitle: brisket Ana

** brisket Ana

  [[[file:0-recipe-index.org][main recipe page]]]

categories: [[[file:c-ana.org][ana]]] [[[file:c-meat.org][meat]]]

 5 lb first cut brisket

 (cook one day, eat next day!)

#+begin_verse
 mix in bowl:
   large container of ketchup
   2 pkgs lipton onion soup mix
   3/4 cup coca cola
   2 dash worcestershire sauce
   mix well

 in dutch oven, with lid:
   brisket
   pour sauce over
   cover tightly
   both aluminum foil and cover -- tight

 cook 4 hours total:
   325F for 2 hours
   take out, turn over
   another 2 hours
   let cool, slice, put back in dutch oven
   eat next day!
#+end_verse

 ===

 Brisket

 purchase 5 lb brisket (we used 2.5lb)

 preheat over to 335 degrees

 season brisket with kosher salt and pepeer

 in a bowl, mix bottle of ketchup, 2 envelopes lipton onion soup mix, 2
 dashes wesheshire saurce, 3/4 cup Coke.

 put brisket in dutch oven

 pour all of ketchup mixture over brisket

 cover dutch over with foil AND lid

 cook 1.5 to 2 hours (depending on how much meat) then turn over and
 cook another 1.5 to 2 hours. 3 to 4 hours total cooking time.

 remove brisket from oven and let rest uncovered c. 15 min

 slice and return to sauce for serving
