#+pagetitle: chickpea curry with basmati rice

** chickpea curry with basmati rice

  [[[file:0-recipe-index.org][main recipe page]]]

category: [[[file:c-indian.org][indian]]]

#+begin_verse
 1     (3.5-ounce) bag boil-in-bag basmati or brown rice
 1     tablespoon canola oil
 1     large onion, diced
 1 1/2 teaspoons garam masala
 2     (15-ounce) cans chickpeas, rinsed and drained
 1     (15-ounce) can unsalted crushed tomatoes
 1     (6-ounce) package fresh baby spinach
 1/2   cup plain 2% Greek yogurt
 1/2   teaspoon salt
 1/4   cup chopped fresh cilantro
#+end_verse

 Cook rice according to package directions; drain.

 While rice cooks, heat a Dutch oven over medium-high heat. Add oil to
 pan; swirl to coat. Add onion; sauté 5 minutes or until tender,
 stirring frequently. Stir in garam masala; cook 30 seconds, stirring
 constantly. Add chickpeas, tomatoes, and spinach; cook 2 minutes or
 until spinach wilts, stirring occasionally. Remove from heat; stir in
 yogurt and salt. Sprinkle with cilantro. Serve over rice.

 source: http://www.myrecipes.com/recipe/chickpea-curry-basmati-rice-50400000125662/
