#+pagetitle: cold sesame noodles with summer vegetables

** cold sesame noodles with summer vegetables

  [[[file:0-recipe-index.org][main recipe page]]]

category: [[[file:c-asian.org][asian]]]

#+begin_verse
 1/3 cup unseasoned rice vinegar
 1/3 cup vegetable oil
 1 tablespoon Sriracha (hot chili sauce)
 1 tablespoon toasted sesame oil
 8 cups matchstick-size pieces mixed summer vegetables 
 (such as carrots, radishes, cucumbers, and bell peppers; about 1 1/4 pounds)
 Kosher salt, freshly ground pepper
 8 ounces buckwheat soba (Japanese-style noodles) or vermicelli noodles
 1 cup (loosely packed) cilantro leaves with tender stems
 3 scallions, thinly sliced
 1 tablespoon black or white sesame seeds

 Whisk first four ingredients in a large bowl. Add vegetables; toss to
 coat. Season with salt and pepper.

 Cook noodles in a large pot of boiling salted water, stirring
 occasionally, until al dente; drain. Run noodles under cold water to
 cool them; drain well and add to bowl with vegetables. Add cilantro
 and scallions; season to taste with salt and pepper. Sprinkle sesame
 seeds over and serve.
#+end_verse

 source:  http://www.epicurious.com/recipes/food/views/51104410
