#+pagetitle: couscous with chicken and olives

** couscous with chicken and olives

  [[[file:0-recipe-index.org][main recipe page]]]

category: [[[file:c-mediterranean.org][mediterranean]]]

#+begin_verse
 8 chicken wings (or some equivalent quantity of chicken)
 scant 1/2 tsp salt
 2 tbsp olive oil
 2 large onions, diced
 4 large garlic cloves, minced
 2 3/4 cups chicken broth
 1/4 cup canned diced tomatoes in juice, pureed
 2 bay leaves
 2 strips (each 2 inches long) lemon zest
 1 whole small dried red chile pepper
 1 inch cinnamon stick
 large pinch saffron threads
 20 pitted green olives
 1 cup cooked chickpeaks
 3 cups cooked Israeli couscous
 1/2 cup raisins
 lemon wedges
#+end_verse

 Sprinkle chicken with a little of the salt.  Heat 1 tbsp of the oil in
 a large Dutch oven.  Add the chicken and saute, turning once, until
 browned, about 8 minutes.  Transfer to a plate, reserve.

 Add remaining 1 tbsp oil to the pan; reduce heat to medium.  Add
 onions and garlic; saute, stirring often, until onions are golden,
 8-10 min.

 Increase heat to high.  Add broth, tomatoes, bay leaves, lemon strips,
 chile, cinnamon, and saffron threads; simmer 3 minutes.

 Add alives and simmer 30 seconds.  Add chicken, stirring to coat with
 sauce.  Cover, reduce heat to medium-low, simmer gently 15 minutes.

 Stir in chickpeas, cover, simmer until chicken is tender, about 10
 minutes.  Season with a little salt if necessary.

 Remove from heat and let stand, covered, 5 minutes.

 Meanwhile, add couscous to a pan of boiling water and heat the grains
 until they are hot all the way through, 1-2 minutes.

 Drain couscous well.  Toss with raisins and make a ring of it on a
 warm platter.  Remove lemon zest, bay leaves, and chile from the
 chicken.  Mound the chicken and all the sauce in the middle of the
 couscous.  Garnish with lemon wedges.
