#+pagetitle: crispy black bean tacos with feta and cabbage slaw

** crispy black bean tacos with feta and cabbage slaw

  [[[file:0-recipe-index.org][main recipe page]]]

category: [[[file:c-mexican.org][mexican]]]

#+begin_verse
      1 15-ounce can black beans, drained
      1/2 teaspoon ground cumin
      5 teaspoons olive oil, divided
      1 tablespoon fresh lime juice
      2 cups coleslaw mix
      2 green onions, chopped
      1/3 cup chopped fresh cilantro
      4 white or yellow corn tortillas
      1/3 cup crumbled feta cheese
      Bottled chipotle hot sauce or other hot sauce
#+end_verse

      (note:  add yellow rice)


 Place beans and cumin in small bowl; partially mash. Mix 2 teaspoons
 olive oil and lime juice in medium bowl; add coleslaw, green onions,
 and cilantro and toss to coat. Season slaw to taste with salt and
 pepper.

 Heat 3 teaspoons olive oil in large nonstick skillet over medium-high
 heat. Add tortillas in single layer. Spoon 1/4 of bean mixture onto
 half of each tortilla; cook 1 minute. Fold tacos in half. Cook until
 golden brown, about 1 minute per side. Fill tacos with feta and
 slaw. Pass hot sauce alongside.
