#+pagetitle: fish pie Jamie Oliver

** fish pie Jamie Oliver

  [[[file:0-recipe-index.org][main recipe page]]]

category: [[[file:c-fish.org][fish]]]

Serves 4.  
 
Start with very fresh fish, bones removed.  Could work with nearly any
sort of fish, but we liked it better with white fish than with salmon.

Note: we replaced potatoes with sweet potatoes --- yum!

 *ingredients*

    - 14 oz sweet potatoes, finely sliced
    - 4 Tbsp olive oil
    - 1 clove garlic, peeled and chopped
    - 1 onion, peeled and sliced
    - 1 bulb fennel (a.k.a. anise), trimmed and sliced
    - 1 tsp fennel seeds
    - 4 medium or 8 small fillets of trout, pinboned
    - 1 1/4 cups light cream
    - 2 handfuls freshly grated parmesan cheese
    - 2 anchovy fillets (basically one can of anchovies)
    - sea salt and freshly ground black pepper
    - 2 handfuls of fresh breadcrumbs (panko works well)
    - 2 lemons, halved


 *directions*

Preheat oven to 400F.  

Boil sliced potatoes in salted boiling water
for a few minutes until softened; then drain in colander.  

Place 8-inch oven-safe pan on low heat and add oil, garlic, onion,
fennel, and fennel seeds.  Cook slowly for 10 minutes with the lid on,
stirring every so often.

Take pan off heat.  Lay fish skin-side-up over onion and fennel.

Mix together cream, parmesan, anchovies; season with salt and pepper;
pour over fish.

Toss potato slices in a little olive oil, salt, and pepper, and layer
these over the top.

Place (uncovered!) in oven for 20 minutes.  5 minutes before end,
sprinkle with breadcrumbs and a bit more grated parmesan.

Serve with lemon halves, a green salad, and cold beers!

source: Jamie Oliver cookbook, via Michelle Komie
