#+pagetitle: fillet of sole with piquant tomato sauce

** fillet of sole with piquant tomato sauce

  [[[file:0-recipe-index.org][main recipe page]]]

category: [[[file:c-fish.org][fish]]]

#+begin_verse
 1/3 c. thinly sliced yellow onion
 2 1/2 Tbsp olive oil
 3/4 tsp finely chopped garlic
 1/2 tsp oregano
 1 Tbsp capers (this are available in a jar, generally in the same
    section of the store as olives and pickles, a small jar will last
    you a long time)
 1/2 c. canned chopped tomatoes and their juice
 Salt to taste
 Black pepper
 1 lb. fresh sole fillets
#+end_verse

- Saute onion in olive oil until soft and pale gold in color.  Add
  garlic and saute until it just starts to turn yellow/light brown.
  Stir in the oregano and capers.  Add tomatoes with juice, salt and
  pepper.  Stir and simmer for 15-20 minutes.

- Rise and dry fish fillets.  Smear bottom of baking dish with a
  little of the tomato sauce (approx. 1 Tbsp).  Dip each fish fillet
  in the sauce, then arrange in baking dish so that fillets are just
  slightly overlapping.  Pour remaining sauce over fish.  Bake in 450
  degree oven for no more than 5-8 minutes (depending on thickness of
  fish).

- If sauce thins during baking (because fish gives off liquid in
  cooking process), pour sauce back into pan and boil rapidly until
  thickened before pouring over fish and serving.
