#+pagetitle: focaccia from Genoa

** focaccia from Genoa

  [[[file:0-recipe-index.org][main recipe page]]]

category: [[[file:c-bread.org][bread]]]

#+begin_verse
 sponge:
 2.5 tsp (1 pkg) active dry yeast
 2/3 c warm water (105-115 degrees)
 1 c unbleached all-purpose flour

 dough:
 1/2 c water, room temperature
 1/3 c white wine (room temp)
 1/3 c olive oil
 2.5 c + 2 tsp flour
 2 tsp salt

 topping:
 2 Tbsp olive oil
 3/4 tsp salt

 sponge:
 Sprinkle yeast over warm water in large bowl, whisk it in, and let
 stand until creamy, about 10 min.  (I usually add a little sugar too,
 to make the yeast foam and check that the water temp was right.)  Stir
 in 1 c flour and beat until smooth.  Cover with plastic wrap and let
 rise about 30 minutes.

 dough:
 Add water, wine, and olive oil to sponge.  Whisk in 1 c flour and
 salt, then beat in rest of flour until dough is soft and sticky.
 Knead on lightly floured board for 6-8 min, until dough is smooth and
 shiny but not wet.  (I often add a couple more Tbsp of flour as needed
 during this process.)

 1st rise:
 Place dough in lightly oiled bowl, cover tightly with plastic wrap,
 and let rise for about 1 hour.

 2nd rise:
 Press dough into lightly oiled 9x13 pan (or 2 cake pans), dimple with
 fingers, cover with towel, and let rise about 45 minutes.

 baking:
 Preheat oven to 425.  Dimple the dough again with fingers, drizzle
 olive oil over top, and sprinkle with salt.  Place focaccia in oven
 and immediately reduce temperature to 400.  Spray sides and floor of
 oven with water 3 times during 1st 10 minutes of baking.  (Just do it
 with your fingertips if you don't have a spray bottle.)  Bake for a
 total of 25-30 minutes until golden.  Immediately remove from pan.
 Serve warm or at room temperature.
#+end_verse

 source: Focaccia cookbook
