#+pagetitle: risotto with mushrooms and peas NYT

** risotto with mushrooms and peas NYT

  [[[file:0-recipe-index.org][main recipe page]]]

categories: [[[file:c-italian.org][italian]]] [[[file:c-nyt.org][nyt]]]

*Ingredients*

- 6--7 cups stock or broth
- 2 Tbsp extra-virgin olive oil
- 2 shallots, minced; or 1/2 cup finely chopped onion if shallots
  aren't available
- 1 pound (just under) wild mushrooms, cleaned and cut into bite-sized
  pieces
- 2 garlic cloves, minced
- 2 tsp fresh thyme leaves or chopped sage
- 1 1/2 cups (1.5 cups) arborio rice
- 1/2 cup dry white wine, e.g. pinot grigio or sauvignon blanc
- 1 cup frozen peas
- 2 Tbsp chopped fresh parsley
- 1/2 cup grated parmesan cheese


*Directions*

1. Simmer stock in a saucepan.  (Pan just needs to be big enough to
   hold the stock.  Choose a shape that makes it easy to ladle out the
   stock.)  Keep it simmering.
2. Heat oil in wide, heavy saucepan over medium heat.  (This pan needs
   to be deep enough to hold the entire risotto.)  Add shallots (or
   onions) and cook gently until just tender, 3--5 minutes.
3. Turn up heat and add mushrooms.  Cook, stirring, until they begin
   to sweat, about 3 minutes, then add garlic and thyme (or sage).
   Cook, stirring, until fragrant, about 30 seconds.  Season mushrooms
   with (salt and) pepper and continue to cook over medium heat until
   they are soft.  Taste and adjust seasoning.
4. Add rice and stir until grains begin to crackle.  Add wine and
   cook, stirring, until wine is no longer visible in pan.  Stir in
   enough simmering stock to just cover the rice.  (Split infinitives
   are OK these days!)  The stock should bubble slowly.  Cook, stiring
   often and vigorously, until stock is just about absorbed.  Add
   another ladle or two of stock and continue cooking, not too fast
   and not too slowly, stirring often and adding more stock when rice
   has absorbed liquid, for 15 minutes.  (Use a spoon or spatula whose
   handle won't blister your fingers!)
5. Add peas and continue adding stock and stirring for another 10
   minutes.  Rice should be tender all the way through but still al
   dente.  Adjust seasoning to taste.
6. Add another ladle or two of stock.  Stir in parsley and parmesan,
   and remove from heat.  Season with black pepper and serve right
   away in wide soup bowls or in plates.

source:  https://cooking.nytimes.com/recipes/1017022-mushroom-risotto-with-peas

This was good.  We cooked it on vacation May 2018.
