#+pagetitle: risotto with tomato and basil

** risotto with tomato and basil

  [[[file:0-recipe-index.org][main recipe page]]]

categories: [[[file:c-italian.org][italian]]] [[[file:c-nyt.org][nyt]]]

#+begin_verse
 7 cups well seasoned vegetable stock, garlic stock or chicken stock
 2 tablespoons extra virgin olive oil
 1/2 cup minced onion
 Salt to taste
 2 garlic cloves, minced
 1 pound tomatoes, grated
 Pinch of sugar
 1 teaspoon fresh thyme leaves
 1 1/2 cups Arborio rice
 Salt and freshly ground pepper to taste
 1/2 cup dry white or rosé wine, such as Pinot Grigio or Sauvignon Blanc
 1/2 pound additional sweet ripe tomatoes, finely diced (about ¾ cup)
 1/4 cup slivered fresh basil
 1/4 to 1/2 cup freshly grated Parmesan cheese (1 to 2 ounces) 
#+end_verse


1. Put your stock or broth into a saucepan and bring it to a simmer
   over low heat, with a ladle nearby or in the pot. Make sure that it
   is well seasoned.

2. Heat the olive oil over medium heat in a wide, heavy skillet or a
   wide, heavy saucepan. Add the onion and a generous pinch of salt, and
   cook gently until tender, about 5 minutes. Add the rice and garlic and
   cook, stirring, until the grains of rice are separate and beginning to
   crackle. Stir in the grated tomatoes, sugar, thyme, and salt to taste
   and cook, stirring often, until the tomatoes have cooked down slightly
   and coat the rice, 5 to 10 minutes.

3. Add the wine and stir until it has evaporated and been absorbed by
   the rice. Begin adding the simmering stock, a couple of ladlefuls
   (about 1/2 cup) at a time. The stock should just cover the rice, and
   should be bubbling, not too slowly but not too quickly. Cook, stirring
   often, until it is just about absorbed. Add another ladleful or two of
   the stock and continue to cook in this fashion, adding more stock and
   stirring when the rice is almost dry. You do not have to stir
   constantly, but stir often and when you do, stir vigorously. When the
   rice is just tender all the way through but still chewy (al dente), in
   20 to 25 minutes, it is done. Taste now and adjust seasoning.

4. Add another ladleful of stock to the rice. Stir in the additional
   finely diced tomatoes, basil and Parmesan and remove from the
   heat. The mixture should be creamy (add more stock if it isn’t). Serve
   right away in wide soup bowls or on plates, spreading the risotto in a
   thin layer rather than a mound.

 source: NYTimes  http://nyti.ms/12Z2TUk
