#+pagetitle: split pea soup

** split pea soup

  [[[file:0-recipe-index.org][main recipe page]]]

category: [[[file:c-soup.org][soup]]]

 So far this is the best of several split-pea soup recipes we've
 tried.  We might have used too much liquid and too much celery
 though.

#+begin_verse
 5 1/2 cups water
 4 cups organic vegetable broth (such as Swanson Certified Organic)
 2 cups green split peas 
 3/4 cup finely chopped yellow onion 
 6 ounces diced Canadian bacon (about 1 cup) 
 1 cup finely chopped carrot 
 1 cup thinly sliced celery 
 1/2 teaspoon freshly ground black pepper
 1/8 teaspoon salt 
 1 tablespoon fresh lemon juice 
#+end_verse

 Combine first 5 ingredients in a large Dutch oven over medium-high 
 heat; bring to a simmer. Cover, reduce heat, and simmer 1 hour, 
 stirring occasionally.

 Stir in carrot, celery, pepper, and salt. Simmer, uncovered, 45 
 minutes or until peas are tender and soup thickens, stirring 
 occasionally. Remove from heat; stir in juice. Serve immediately.

 source: http://www.myrecipes.com/recipe/split-pea-soup-10000001662878/
