#+pagetitle: tangy spicy green beans

** tangy spicy green beans

  [[[file:0-recipe-index.org][main recipe page]]]

category: [[[file:c-asian.org][asian]]]

#+begin_verse
 1 lb fresh green beans
 2 tbsp canola oil
 1/3 cup water
 1 small onion, finely chopped
 2 cloves minced fresh garlic
 2 tbsp fresh chopped ginger
 1 tsp dried shredded lemon grass
 1 tbsp corn starch
 2 tbsp seasoned rice vinegar
 1 tbsp soy sauce
 1 cup chicken stock
 pepper (black, cayenne, szechwan, etc.)

 trim and rinse beans.  in wok, heat oil over high heat until it begins
 to smoke.  quickly add beans to oil, don't spatter.  add water and
 cover quickly, before water spatters all over kitchen.

 steam-fry beans 5 minutes, shaking covered pan now and then.  lift
 lid, add onion, garlic, ginger, lemon grass.  stir, toss, cover,
 steam-fry another 2-3 minutes.

 blend corn starch and vinegar.  blend in remaining ingredients.
 remove lid, stir-fry 1 minute, add liquid, stir-fry until sauce
 thickens and beans are tender but firm.
#+end_verse
