#+pagetitle: tofu broccoli stir fry

** tofu broccoli stir fry

  [[[file:0-recipe-index.org][main recipe page]]]

category: [[[file:c-asian.org][asian]]]

- Ingredients (Serves 4)

  * 1 package (14 1/2 ounces) firm tofu, drained, cut crosswise into
    6 slabs (about 3/4 inch wide), each slab halved horizontally and cut
    into triangles
  * 1 1/2 pounds broccoli, stalks trimmed, peeled, and cut into
    1/4-inch rounds, florets separated into bite-size pieces
  * Coarse salt
  * 2 tablespoons vegetable oil
  * 3 tablespoons soy sauce
  * 2 tablespoons rice vinegar
  * 1/4 teaspoon red-pepper flakes
  * 4 garlic cloves, minced
  * 1 tablespoon cornstarch
  * 1/2 cup cashews, toasted

- Directions

  - Arrange tofu in a single layer on a baking sheet lined with
    several layers of paper towels. Top with more paper towels and
    another baking sheet; weight with canned goods. Let tofu drain,
    about 20 minutes.

  - Meanwhile, cook broccoli (stalks and florets) in a large pot of
    boiling salted water until bright green, 2 minutes. Drain; set aside.

  - Heat oil in a large nonstick skillet over medium heat. Add tofu;
    cook until golden brown, turning gently halfway through, 10 to 15
    minutes. Transfer to paper towels.

  - Meanwhile, make sauce: In a small bowl, whisk together soy
    sauce, vinegar, red-pepper flakes, garlic, cornstarch, and 3/4 cup
    water; set aside.

  - Add broccoli to skillet; cook over high heat, stirring often,
    until crisp-tender, 2 to 3 minutes. Whisk reserved sauce to combine;
    pour into pan. Return tofu to pan; stir to coat, about 1 minute
    more. Serve topped with cashews.

 source:  marthastewart.com
