#+pagetitle: whole wheat focaccia

** whole wheat focaccia

  [[[file:0-recipe-index.org][main recipe page]]]

category: [[[file:c-bread.org][bread]]]

: 
:  sponge:                               dough:                         
:     1  tsp active dry yeast               1   tsp active dry yeast   
:    1/2 cup warm water (105-115 F)         1   cup warm water         
:    3/4 cup flour                        2 1/2 cup flour              
:                                          3/4  cup whole-wheat flour  
:                                           3   tbsp olive oil         
:                                           2   tsp salt               
:                                           1   sponge                 
: 

 To make sponge:  Mix yeast and water and let stand until creamy (10
 min).  Stir in flour, cover tightly with plastic wrap, and let rise 45
 min until doubled.

 To make dough:  Mix yeast and water and let stand until creamy.  Add
 yeast mixture and olive oil to sponge and mix well.  Stir in salt and
 add flours one cup at a time until soft dough is formed.  Knead on
 floured surface 8-10 min.  Put dough in lightly oiled bowl, cover with
 plastic wrap, and let rise 1 1/4 hours.

 To shape dough:  Oil an 11x17 baking sheet or 2 pie pans.  Flatten
 dough and spread it in pan(s), allowing it to relax for 10 min if it
 will not reach edges.  Cover with towel or plastic wrap and let rise
 for 45 min.

 To bake:  Preheat oven to 425 F 30 min before baking.  Dimple dough
 with finger tips, drizzle it with 1-2 tbsp oil, and sprinkle with sea
 salt.  Bake 20-25 min.

 For crispier crust:  Spray oven walls with cold water 3 times during
 first 10 min of baking.

 Source: Focaccia cookbook
